import React,{useEffect,useState} from "react";
import {Building2,CheckCircle2,HeartPulse,LayoutDashboard,LogOut,RefreshCw,ShieldCheck,Stethoscope,XCircle} from "lucide-react";
import {useNavigate} from "react-router-dom";
import {api} from "../api/client";
import "./admin.css";

const sections=[["dashboard","Dashboard",LayoutDashboard],["hospital-pending","Hospital Verification",Building2],["hospital-verified","Verified Hospitals",ShieldCheck],["doctor-pending","Doctor Verification",Stethoscope],["doctor-verified","Verified Doctors",CheckCircle2]];
export default function AdminPortal(){const [view,setView]=useState("dashboard"),[records,setRecords]=useState({pendingHospitals:[],verifiedHospitals:[],pendingDoctors:[],verifiedDoctors:[]}),[error,setError]=useState(""),[success,setSuccess]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");const navigate=useNavigate();
  const load=async()=>{setLoading(true);setError("");try{const [pendingHospitals,verifiedHospitals,pendingDoctors,verifiedDoctors]=await Promise.all([api("/admin/hospitals/pending"),api("/admin/hospitals/verified"),api("/admin/doctors/pending"),api("/admin/doctors/verified")]);setRecords({pendingHospitals,verifiedHospitals,pendingDoctors,verifiedDoctors})}catch(reason){setError(reason.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const act=async(path,id,verb)=>{if(verb==="rejected"&&!window.confirm("Reject this verification request?"))return;setBusy(id);setSuccess("");try{await api(path,{method:"PATCH"});setSuccess(`Record ${verb} successfully.`);await load()}catch(reason){setError(reason.message)}finally{setBusy("")}};
  return <div className="admin-shell"><aside><div className="brand"><span><HeartPulse/></span>CityCare</div><p className="role">ADMIN PORTAL</p><nav>{sections.map(([key,label,Icon])=><button className={view===key?"nav-active":""} onClick={()=>setView(key)} key={key}><Icon/>{label}</button>)}</nav><button className="logout" onClick={()=>{localStorage.clear();navigate("/login")}}><LogOut/>Logout</button></aside><main><header><div><p className="eyebrow">SYSTEM ADMINISTRATION</p><h2>Verification centre</h2></div><button className="outline refresh" onClick={load}><RefreshCw/>Refresh</button></header>{success&&<div className="success">{success}</div>}{error&&<div className="error">{error}</div>}{loading?<p className="muted">Loading verification records…</p>:<Content view={view} records={records} busy={busy} act={act}/>}</main></div>}
function Content({view,records,busy,act}){if(view==="dashboard")return <><section className="welcome"><div><p className="eyebrow">TRUST & SAFETY</p><h1>CityCare network overview.</h1><p>Verify healthcare organisations and professional identities while preserving hospital-level doctor approval.</p></div></section><div className="stat-grid"><Stat label="Pending Hospitals" value={records.pendingHospitals.length}/><Stat label="Verified Hospitals" value={records.verifiedHospitals.length}/><Stat label="Pending Doctors" value={records.pendingDoctors.length}/><Stat label="Verified Doctors" value={records.verifiedDoctors.length}/></div></>;
  if(view==="hospital-pending")return <Section title="Hospital Verification" empty="No hospitals are waiting for verification." items={records.pendingHospitals} render={item=><><h3>{item.name}</h3><p>{item.email}</p><p className="muted">{item.address}, {item.city}, {item.state}<br/>Registration: {item.registration_number}</p><span className="badge booked">{item.verification_status}</span><details><summary>View details</summary><p>{item.description}</p><div className="tags">{item.specializations?.map(x=><span key={x}>{x}</span>)}</div></details><Actions disabled={busy===item.id} approve={()=>act(`/admin/hospitals/${item.id}/verify`,item.id,"verified")} reject={()=>act(`/admin/hospitals/${item.id}/reject`,item.id,"rejected")}/></>}/>;
  if(view==="hospital-verified")return <Section title="Verified Hospitals" empty="No hospitals have been verified yet." items={records.verifiedHospitals} render={item=><><h3>{item.name}</h3><p>{item.email}</p><p className="muted">{item.address}, {item.city}, {item.state}<br/>Registration: {item.registration_number}</p><span className="badge confirmed">{item.verification_status}</span><details><summary>View details</summary><p>{item.description}</p></details></>}/>;
  if(view==="doctor-pending")return <Section title="Doctor Verification" empty="No doctors are waiting for verification." items={records.pendingDoctors} render={item=><><h3>Dr. {item.first_name} {item.last_name}</h3><p>{item.email}</p><p>{item.specialization} · {item.qualification}</p><p className="muted">License: {item.medical_registration_number}</p><span className="badge booked">{item.verification_status}</span><Actions disabled={busy===item.id} approve={()=>act(`/admin/doctors/${item.id}/verify`,item.id,"verified")} reject={()=>act(`/admin/doctors/${item.id}/reject`,item.id,"rejected")}/></>}/>;
  return <Section title="Verified Doctors" empty="No doctors have been verified yet." items={records.verifiedDoctors} render={item=><><h3>Dr. {item.first_name} {item.last_name}</h3><p>{item.email}</p><p>{item.specialization}</p><p className="muted">License: {item.medical_registration_number}</p><span className="badge confirmed">Admin: {item.admin_verification_status}</span><h4>Hospital affiliation</h4>{item.affiliations?.length?item.affiliations.map((affiliation,index)=><p className="affiliation" key={`${affiliation.hospital_id}-${index}`}><b>{affiliation.hospital_name}</b><span className={`badge ${affiliation.hospital_approval_status==="approved"?"confirmed":"booked"}`}>{affiliation.hospital_approval_status}</span></p>):<p className="muted">No hospital affiliation request.</p>}<details><summary>View details</summary><p>{item.qualification} · {item.experience} years</p></details></>}/>}
function Section({title,empty,items,render}){return <section><div className="section-title"><div><h1>{title}</h1><p className="muted">{items.length} record{items.length===1?"":"s"}</p></div></div>{items.length?<div className="review-grid">{items.map(item=><article className="panel review-card" key={item.id}>{render(item)}</article>)}</div>:<div className="empty"><ShieldCheck/><h3>{empty}</h3></div>}</section>}
function Actions({approve,reject,disabled}){return <div className="review-actions"><button className="primary" onClick={approve} disabled={disabled}><CheckCircle2/>Verify</button><button className="danger" onClick={reject} disabled={disabled}><XCircle/>Reject</button></div>}
function Stat({label,value}){return <article className="panel stat"><p>{label}</p><strong>{value}</strong></article>}
