import React,{useEffect,useState} from "react";
import {Building2,CalendarDays,CheckCircle2,ClipboardCheck,HeartPulse,LayoutDashboard,LogOut,Stethoscope,UserRound,XCircle} from "lucide-react";
import {Link,useNavigate} from "react-router-dom";
import {api} from "../api/client";
import "./role-portals.css";

const links=[["/hospital","Dashboard",LayoutDashboard],["/hospital/requests","Doctor Requests",ClipboardCheck],["/hospital/doctors","Verified Doctors",Stethoscope],["/hospital/appointments","Appointments",CalendarDays],["/hospital/profile","Hospital Profile",Building2]];
export default function HospitalPortal({view="dashboard"}){
  const [data,setData]=useState(null),[error,setError]=useState(""),[success,setSuccess]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");const navigate=useNavigate();
  const endpoints={dashboard:"/hospital/dashboard",requests:"/hospital/doctor-requests",doctors:"/hospital/doctors/verified",appointments:"/hospital/appointments",profile:"/hospital/profile"};
  const load=()=>{setLoading(true);setError("");return api(endpoints[view]).then(setData).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))};useEffect(()=>{let active=true;setLoading(true);setError("");api(endpoints[view]).then(result=>{if(active)setData(result)}).catch(reason=>{if(active)setError(reason.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[view]);
  const review=async(item,action)=>{if(action==="reject"&&!window.confirm(`Reject Dr. ${item.doctor.first_name} ${item.doctor.last_name}'s request?`))return;setBusy(item.id);setSuccess("");try{await api(`/hospital/doctor-requests/${item.id}/${action}`,{method:"PATCH"});setSuccess(`Doctor request ${action==="approve"?"approved":"rejected"} successfully.`);await load()}catch(reason){setError(reason.message)}finally{setBusy("")}};
  return <RoleShell label="HOSPITAL PORTAL" links={links} logout={()=>{localStorage.clear();navigate("/login")}}><PageHeading view={view}/>{success&&<div className="success">{success}</div>}{error&&<div className="error">{error}</div>}{loading?<Loading/>:<HospitalContent view={view} data={data} review={review} busy={busy}/>}</RoleShell>
}
function PageHeading({view}){const titles={dashboard:["Hospital overview","Your doctors, requests and appointments at a glance."],requests:["Doctor requests","Review doctors requesting affiliation with your hospital."],doctors:["Verified doctors","Doctors approved specifically by your hospital."],appointments:["Hospital appointments","Appointments belonging only to your hospital."],profile:["Hospital profile","Your verified hospital information."]};return <div className="page-heading"><p className="eyebrow">HOSPITAL MANAGEMENT</p><h1>{titles[view][0]}</h1><p className="muted">{titles[view][1]}</p></div>}
function HospitalContent({view,data,review,busy}){
  if(view==="dashboard"){const stats=data?.stats||{};return <><div className="stat-grid"><Stat label="Total Verified Doctors" value={stats.total_verified_doctors}/><Stat label="Pending Doctor Requests" value={stats.pending_doctor_requests}/><Stat label="Today's Appointments" value={stats.todays_appointments}/><Stat label="Upcoming Appointments" value={stats.upcoming_appointments}/></div><section className="panel"><h2>Today’s activity</h2>{data?.todays_appointments?.length?<AppointmentRows items={data.todays_appointments}/>:<Empty icon={CalendarDays} text="No appointments scheduled for today."/>}</section></>}
  if(view==="requests")return data?.length?<div className="review-grid">{data.map(item=><article className="panel doctor-request" key={item.id}><div className="request-head"><div className="doctor-avatar"><UserRound/></div><div><h3>Dr. {item.doctor.first_name} {item.doctor.last_name}</h3><p>{item.doctor.email}</p></div><span className="badge booked">{item.request_status}</span></div><dl><dt>Specialization</dt><dd>{item.doctor.specialization}</dd><dt>Qualification</dt><dd>{item.doctor.qualification}</dd><dt>Experience</dt><dd>{item.doctor.experience} years</dd><dt>Registration</dt><dd>{item.doctor.medical_registration_number||"Not provided"}</dd><dt>Admin status</dt><dd>{item.doctor.admin_verification_status}</dd></dl><details><summary>View details</summary><p>{item.doctor.bio||"No professional biography provided."}</p></details><div className="review-actions"><button className="primary" disabled={busy===item.id} onClick={()=>review(item,"approve")}><CheckCircle2/>Approve</button><button className="danger" disabled={busy===item.id} onClick={()=>review(item,"reject")}><XCircle/>Reject</button></div></article>)}</div>:<Empty icon={ClipboardCheck} text="No pending doctor affiliation requests."/>
  if(view==="doctors")return data?.length?<div className="review-grid">{data.map(doctor=><article className="panel doctor-request" key={doctor.id}><div className="request-head"><div className="doctor-avatar"><UserRound/></div><div><h3>Dr. {doctor.first_name} {doctor.last_name}</h3><p>{doctor.email}</p></div><span className="badge confirmed">Active</span></div><p><b>{doctor.specialization}</b></p><p className="muted">{doctor.mobile}<br/>{doctor.experience} years experience</p><details><summary>View profile</summary><p>{doctor.qualification}</p><p>{doctor.bio||"No biography provided."}</p></details></article>)}</div>:<Empty icon={Stethoscope} text="No doctors have been approved by this hospital yet."/>
  if(view==="appointments")return data?.length?<AppointmentRows items={data}/>:<Empty icon={CalendarDays} text="No appointments found for this hospital."/>
  return data?<div className="panel profile-panel"><div className="hospital-logo large"><Building2/></div><span className={`badge ${data.verification_status==="verified"?"confirmed":"booked"}`}>{data.verification_status}</span><h2>{data.name}</h2><p>{data.email} · {data.mobile}</p><p className="muted">{data.address}, {data.city}, {data.state} — {data.pincode}</p><h3>Registration</h3><p>{data.registration_number}</p><h3>Specializations</h3><div className="tags">{data.specializations?.map(value=><span key={value}>{value}</span>)}</div></div>:null
}
function AppointmentRows({items}){return <div className="table-wrap"><table><thead><tr><th>Patient</th><th>Doctor</th><th>Date</th><th>Time</th><th>Reason</th><th>Status</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.patient?.name||"Patient"}</td><td>{item.doctor?.name||"Doctor"}</td><td>{item.date}</td><td>{item.slot}</td><td>{item.reason}</td><td><span className={`badge ${item.status}`}>{item.status==="booked"?"pending":item.status}</span></td></tr>)}</tbody></table></div>}
function Stat({label,value=0}){return <article className="panel stat"><p>{label}</p><strong>{value||0}</strong></article>}
function Empty({icon:Icon,text}){return <div className="empty compact"><Icon/><h3>{text}</h3></div>}
function Loading(){return <p className="muted">Loading hospital workspace…</p>}
export function RoleShell({label,links,logout,children}){return <div className="role-shell"><aside><div className="brand"><span><HeartPulse/></span>CityCare</div><p className="role">{label}</p><nav>{links.map(([to,text,Icon])=><Link to={to} key={to}><Icon/>{text}</Link>)}</nav><button className="logout" onClick={logout}><LogOut/>Logout</button></aside><main>{children}</main></div>}
