"""Generate a professional prescription PDF in memory for viewing/download."""
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas


def prescription_pdf(prescription: dict) -> bytes:
    buffer=BytesIO(); pdf=canvas.Canvas(buffer,pagesize=A4); width,height=A4
    patient=prescription.get("patient") or {}; doctor=prescription.get("doctor") or {}; hospital=prescription.get("hospital") or {}; appointment=prescription.get("appointment") or {}
    pdf.setFillColor(HexColor("#087b68")); pdf.rect(0,height-95,width,95,fill=1,stroke=0)
    pdf.setFillColorRGB(1,1,1); pdf.setFont("Helvetica-Bold",22); pdf.drawString(48,height-55,"CityCare Prescription")
    pdf.setFont("Helvetica",10); pdf.drawString(48,height-75,"Verified care record")
    y=height-130; pdf.setFillColor(HexColor("#17352d")); pdf.setFont("Helvetica-Bold",11)
    details=[("Patient",patient.get("name") or "Patient"),("Doctor",doctor.get("name") or "Doctor"),("Hospital",hospital.get("name") or "Hospital"),("Appointment",f"{appointment.get('date') or ''} at {appointment.get('slot') or ''}")]
    for label,value in details: pdf.drawString(48,y,f"{label}:"); pdf.setFont("Helvetica",11); pdf.drawString(125,y,str(value)[:75]); pdf.setFont("Helvetica-Bold",11); y-=21
    y-=10; pdf.setFillColor(HexColor("#087b68")); pdf.setFont("Helvetica-Bold",13); pdf.drawString(48,y,"Diagnosis"); y-=22
    pdf.setFillColor(HexColor("#17352d")); pdf.setFont("Helvetica",11); pdf.drawString(48,y,str(prescription.get("diagnosis") or "Not specified")[:90]); y-=34
    pdf.setFillColor(HexColor("#087b68")); pdf.setFont("Helvetica-Bold",13); pdf.drawString(48,y,"Medicines"); y-=24
    pdf.setFillColor(HexColor("#17352d")); pdf.setFont("Helvetica",10)
    for medicine in prescription.get("medicines",[]):
        if isinstance(medicine,dict): line=f"- {medicine.get('name','Medicine')} | {medicine.get('dosage','')} | {medicine.get('frequency','')} | {medicine.get('duration','')}"
        else: line=f"- {medicine}"
        pdf.drawString(48,y,line[:105]); y-=20
    y-=12; pdf.setFillColor(HexColor("#087b68")); pdf.setFont("Helvetica-Bold",13); pdf.drawString(48,y,"Instructions"); y-=22
    pdf.setFillColor(HexColor("#17352d")); pdf.setFont("Helvetica",10)
    instructions=str(prescription.get("instructions") or "Not specified")
    for start in range(0,len(instructions),100): pdf.drawString(48,y,instructions[start:start+100]); y-=17
    y-=10; pdf.setFont("Helvetica-Bold",10); pdf.drawString(48,y,"Follow-up:"); pdf.setFont("Helvetica",10); pdf.drawString(115,y,str(prescription.get("follow_up") or "Not specified")[:80])
    pdf.setFillColor(HexColor("#6b837b")); pdf.setFont("Helvetica",8); pdf.drawString(48,42,"This prescription was generated by CityCare. Follow your doctor's instructions.")
    pdf.save(); buffer.seek(0); return buffer.getvalue()
